Repository soohwan93/codeit-part4-team14-GlobalNomad, pull requests merged in 2024-05, with the labels that each got.

#51 [PFTF-50] cookie 함수 수정
  util/cookieSetting.ts
Labels: refactor

#52 [PFTF-46] 공통 api 세팅
  api.http
  util/api.ts
  util/apiType.ts
  util/querySetting.ts
Labels: setting

#55 [PFTF-54] 잘못된 폴더 경로 수정
  app/(app)/activity-detail/page.tsx
  app/(app)/activity-management/create/page.tsx
  app/(app)/activity-management/page.tsx
Labels: refactor

#57 [PFTF-9] color 세팅 작업
  app/(app)/activity-management/page.tsx
  components/test/ColorTest.tsx
  tailwind.config.ts
Labels: setting

#56 [PFTF-23] 버튼 컴포넌트 작업 완료
  components/common/Button.tsx
  package-lock.json
  package.json
  util/tailwindClassMerge.ts
Labels: component

#61 [PFTF-60] 쿠키 로직 변경에 따른 api 함수 수정
  app/(app)/activity-management/page.tsx
  app/(app)/layout.tsx
  app/(auth)/layout.tsx
  app/api/fetchWithToken/route.ts
  app/api/login/route.ts
  app/api/logout/route.ts
  components/test/ApiTest1.tsx
  components/test/ApiTest2.tsx
  package-lock.json
  package.json
  util/api.ts
  util/cookieSetting.ts
Labels: refactor

#59 [PFTF-21] input형 드롭다운 컴포넌트 작성
  components/common/useDropdownInput.tsx
  public/icons/checkmark.svg
  public/icons/chevron_down.svg
Labels: component

#64 [PFTF-13] SubButton 컴포넌트 작업
  app/(app)/activity-management/page.tsx
  components/activity-management/AddImage.tsx
  components/common/svg/AddImageSvg.tsx
  components/common/svg/AlertSvg.tsx
  components/common/svg/EyeOffSvg.tsx
  components/common/svg/EyeOnSvg.tsx
  components/common/svg/InteractiveMinusSvg.tsx
  components/common/svg/InteractivePlusSvg.tsx
  components/common/svg/InteractiveRoundedCloseSvg.tsx
  components/common/svg/KebabSvg.tsx
  components/common/svg/MinusLargeSvg.tsx
  components/common/svg/MinusSmallSvg.tsx
  components/common/svg/PlainCloseSvg.tsx
  components/common/svg/PlusLargeSvg.tsx
  components/common/svg/PlusSmallSvg.tsx
  components/common/svg/RoundedCloseSvg.tsx
  components/test/SubButtonTest.tsx
  public/icons/addImage.svg
  public/icons/alert.svg
  public/icons/eye-off.svg
  public/icons/eye-on.svg
  public/icons/kebab.svg
  public/icons/minusLarge.svg
  public/icons/minusSmall.svg
  public/icons/plainClose.svg
  public/icons/plusLarge.svg
  public/icons/plusSmall.svg
  public/icons/roundedClose.svg
Labels: component

#63 [PFTF-20] pagination 컴포넌트 작업
  components/common/Pagination/index.tsx
  components/common/svg/Arrow.tsx
  public/icons/arrow.svg
Labels: component

#66 [PFTF-14] logo 이미지 작업
  app/(app)/activity-management/page.tsx
  components/common/svg/AuthLogoSvg.tsx
  components/common/svg/HeaderLogoSvg.tsx
  components/test/LogoTest.tsx
  public/icons/authLogo.svg
  public/icons/headerLogo.svg
Labels: setting
