Repository soohwan93/codeit-part4-team14-GlobalNomad, pull requests merged in 2024-06, with the labels that each got.

#67 [PFTF-16] Search 컴포넌트 UI 작업완료
  components/common/Search.tsx
  components/common/svg/SearchLogoSvg.tsx
  public/icons/search_logo.svg
Labels: component

#65 [PFTF-18] Input 컴포넌트 작업
  components/common/Input.tsx
  components/test/InputTest.tsx
Labels: component

#72 [PFTF-28][PFTF-29] 체험 Card - 예약 내역 / 내 체험 관리
  app/(app)/test-card/page.tsx
  components/activity-management/ActivityManagementCard.tsx
  components/common/ACTIVITY_LIST.ts
  components/common/RESERVATION_DATA.ts
  components/reservation-status/ReservationListCard.tsx
Labels: component

#62 [PFTF-39] Dropdown 컴포넌트 작업
  components/common/Dropdown.tsx
Labels: component

#68 [PFTF-43][PFTF-25] 예약 모달 컴포넌트 ui및 기초 로직 구현 / 공용 modal 컴포넌트 구현
  app/(app)/activity-detail/[activityId]/page.tsx
  app/(app)/globals.css
  app/(app)/layout.tsx
  components/activity-detail/ReservationModal/ReservationCounter/ReservationCounter.tsx
  components/activity-detail/ReservationModal/ReservationCounter/ReservationCounterPresenter.tsx
  components/activity-detail/ReservationModal/ReservationDate/ReservationDate.tsx
  components/activity-detail/ReservationModal/ReservationDate/ReservationDatePresenter.tsx
  components/activity-detail/ReservationModal/calendarTypes.ts
  components/activity-detail/ReservationModal/index.tsx
  components/common/ModalPortal.tsx
  package-lock.json
  package.json
  public/icons/btn_X.svg
  public/icons/counter/Add.svg
  public/icons/counter/Subtract.svg
Labels: component

#70 [PFTF-19] Category 컴포넌트 구현완료
  components/common/Category.tsx
Labels: component

#78 [PFTF-32][PFTF-33] 로그인, 회원가입 페이지
  app/(auth)/layout.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  components/common/svg/AuthMainLogo.tsx
  components/signIn/SignInForm.tsx
  components/signup/SignupForm.tsx
  contexts/NotificationContext.tsx
  hooks/useFormValidation.ts
  public/data/badwords.json
  util/validation.ts
Labels: component, page

#83 [PFTF-82]next-auth 적용
  .env
  app/(app)/activity-management/page.tsx
  app/(app)/layout.tsx
  app/(app)/test-card/page.tsx
  app/(auth)/layout.tsx
  app/api/auth/[...nextauth]/route.ts
  app/api/fetchWithToken/route.ts
  app/api/login/route.ts
  app/api/logout/route.ts
  auth.config.ts
  auth.ts
  auth.util.ts
  components/activity-management/ActivityManagementCard.tsx
  components/activity-management/ActivityManagementCardWrapper.tsx
  components/activity-management/ActivityManagementHeader.tsx
  components/common/GNB.tsx
  components/common/GNB/AuthNavButtons.tsx
  components/common/GNB/GuestNavButtons.tsx
  components/common/GNB/NavButtons.tsx
  components/common/GNB/UserInformation.tsx
  components/common/Header.tsx
  components/common/svg/AlertSvg.tsx
  components/common/svg/CaretSvg.tsx
  components/common/svg/DivineLineSvg.tsx
  components/signIn/SignInForm.tsx
  components/test/LoginTest.tsx
  components/test/SubButtonTest.tsx
  contexts/SessionProviderWrapper.tsx
  custom.d.ts
  middleware.ts
  next-auth.d.ts
  next.config.mjs
  package-lock.json
  package.json
  public/icons/caret-down.svg
  public/icons/devine-line.svg
  public/icons/userNoImage.svg
  tailwind.config.ts
  util/actions.ts
  util/api.ts
  util/apiType.ts
Labels: refactor, setting

#81 [PFTF-80] modalPortal 리렌더링 픽스
  components/common/ModalBase.tsx
  components/common/ModalPortal.tsx
Labels: bug, component

#85 [PFTF-84] Dropdown 컴포넌트에 누락된 onClick관련 기능 추가
  components/common/Dropdown.tsx
Labels: component

#88 [PFTF-12] Footer컴포넌트 작성
  components/common/Footer.tsx
  components/common/svg/FooterFacebookSvg.tsx
  components/common/svg/FooterInstagramSvg.tsx
  components/common/svg/FooterTwitterSvg.tsx
  components/common/svg/FooterYoutubeSvg.tsx
  components/common/svg/HeaderLogoSvg.tsx
  next.config.mjs
Labels: component

#74 [PFTF-22,39] FilterDropdown 제작
  components/common/FilterDropdown.tsx
Labels: component

#92 [PFTF-40] 내 체험 등록/수정 페이지 작업
  app/(app)/activity-management/[activityId]/page.tsx
  app/(app)/activity-management/create/page.tsx
  app/(app)/layout.tsx
  components/activity-management/AddImage.tsx
  components/activity-management/createOrUpdate/ActivityCreateOrUpdateForm.tsx
  components/activity-management/createOrUpdate/ActivityCreateOrUpdateHeader.tsx
  components/activity-management/createOrUpdate/CreateOrUpdateMain.tsx
  components/activity-management/createOrUpdate/CreateOrUpdateWrapper.tsx
  components/activity-management/createOrUpdate/ImageInputs.tsx
  components/activity-management/createOrUpdate/ReservationTimeInputs.tsx
  components/common/Dropdown.tsx
  components/common/Label.tsx
  components/common/ModalBase.tsx
  components/common/Popup/PopupWrapper.tsx
  components/common/svg/InteractivePlusSvg.tsx
  components/common/svg/InteractiveRoundedCloseSvg.tsx
  components/common/svg/MinusSmallSvg.tsx
  components/common/svg/PlusSmallSvg.tsx
  components/common/svg/RoundedCloseSvg.tsx
  components/common/useDropdownInput.tsx
  components/test/SubButtonTest.tsx
  package-lock.json
  package.json
  public/images/noImage.webp
  tailwind.config.ts
  tsconfig.json
  util/actions.ts
  util/api.ts
  util/apiType.ts
  util/constraints.ts
  util/formatSchedule.ts
  util/validation.ts
Labels: page

#90 [PFTF-41] 알림 모달 제작
  app/(app)/page.tsx
  components/common/NotificationModal/NotificationModal.tsx
  components/common/Popup/NotificationPopup.tsx
  components/common/ReviewModal/ReviewModal.tsx
  components/common/ReviewModal/ReviewType.ts
  components/common/ReviewModal/Star.tsx
  components/common/ReviewModal/StarRating.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  tsconfig.json
  util/dateForm.ts
Labels: component

#75 [PFTF-11] gnb 컴포넌트 작업
  components/common/Dropdown.tsx
  components/common/GNB.tsx
  components/common/GNB/AuthNavButtons.tsx
  components/common/GNB/NavButtons.tsx
  components/common/GNB/OptionalNav.tsx
  components/common/GNB/UserInformation.tsx
  components/common/GNB/auth/AlertMenu.tsx
  components/common/GNB/auth/AuthMenu.tsx
  components/common/GNB/auth/UserImage.tsx
  components/common/GNB/auth/UserInformation.tsx
  components/common/GNB/auth/UserMenu.tsx
  components/common/GNB/auth/UserSkeleton.tsx
  components/common/GNB/navType/AuthNav.tsx
  components/common/GNB/navType/GuestNav.tsx
  components/common/NotificationModal/NotificationModal.tsx
  components/common/svg/AlertSvg.tsx
  components/test/SubButtonTest.tsx
  package-lock.json
  package.json
  util/actions.ts
Labels: component

#94 [PFTF-36] 내 체험 관리 페이지 작업
  app/(app)/activity-management/page.tsx
  app/(app)/loading.tsx
  app/(app)/test-card/page.tsx
  app/api/deleteMyActivity/[...activityId]/route.ts
  components/activity-management/ActivityManagementCard.tsx
  components/activity-management/ActivityManagementCardWrapper.tsx
  components/activity-management/ActivityManagementHeader.tsx
  components/activity-management/ActivityManagementKebab.tsx
  components/activity-management/ActivityManagementWrapper.tsx
  components/activity-management/createOrUpdate/ActivityCreateOrUpdateHeader.tsx
  components/activity-management/createOrUpdate/CreateOrUpdateWrapper.tsx
  components/common/Dropdown.tsx
  components/common/Popup/CancelPopup.tsx
  components/common/Popup/DeletePopup.tsx
  components/common/Popup/NotificationPopup.tsx
  components/common/Popup/PopupWrapper.tsx
  contexts/NotificationContext.tsx
  package-lock.json
  package.json
  util/actions.ts
  util/apiType.ts
Labels: page

#93 [PFTF-44] 예약 현황 페이지 작업
  app/(app)/reservation-status/page.tsx
  components/reservation-status/ReservationCalendar.tsx
  components/reservation-status/ReservationModalContents/ReservationCard.tsx
  components/reservation-status/ReservationModalContents/ReservationCardList.tsx
  components/reservation-status/ReservationModalContents/ReservationTypeSelector.tsx
  components/reservation-status/ReservationModalContents/index.tsx
  components/reservation-status/ReservationStatus.tsx
  components/reservation-status/StatusChip.tsx
  components/reservation-status/StatusChipList.tsx
  components/reservation-status/useCalendar.tsx
  components/test/LoginTest.tsx
  package-lock.json
  package.json
  public/icons/loading.png
  public/icons/no-result.svg
  util/apiType.ts
Labels: page

#89 [PFTF-34] 내 정보 페이지
  app/(app)/my-page/page.tsx
  components/common/svg/DefaultUserSvg.tsx
  components/common/svg/ProfileEditSvg.tsx
  components/my-page/MyInfo.tsx
  components/my-page/ProfileImageUploader.tsx
  hooks/useFormValidation.ts
  util/api.ts
  util/apiType.ts
Labels: page

#79 [PFTF-42] 리뷰 모달 컴포넌트 작업
  components/common/ReviewModal/ReviewModal.tsx
  next.config.mjs
  package-lock.json
  package.json
  tailwind.config.ts
Labels: component

#86 [PFTF-35] 메인 페이지 UI 구현
  app/(app)/page.tsx
  components/common/Banner.tsx
  components/common/CardResource.tsx
  components/common/Category.tsx
  components/common/Pagination/index.tsx
  components/common/Search.tsx
  components/common/svg/DropdownArrowSvg2.tsx
  components/test/ActivityList.tsx
  next.config.mjs
  public/icons/dropdown-arrow.svg
  tailwind.config.ts
Labels: page

#98 [PFTF-11] gnb 컴포넌트 작업 (NotificationModal 관련)
  components/common/NotificationModal/NotificationModal.tsx
  package-lock.json
  package.json
Labels: component

#103 [PFTF-102]/[PFTF-104] Header, 내 체험 버그 리팩토링
  app/(app)/activity-management/page.tsx
  app/api/updateMyActivity/[...activityId]/route.ts
  components/activity-management/ActivityManagementCardWrapper.tsx
  components/activity-management/createOrUpdate/ImageInputs.tsx
  components/common/Dropdown.tsx
  components/common/GNB.tsx
  util/actions.ts
  util/constraints.ts
Labels: refactor

#101 [PFTF-37] 예약 내역 페이지 작업
  app/(app)/reservations/page.tsx
  components/common/FilterDropdown.tsx
  components/reservation/ReservationCanvanCard.tsx
Labels: page

#108 [PFTF-107] 메인 페이지 수정 및 리팩토링
  app/(app)/page.tsx
  components/common/Banner.tsx
  components/common/CardResource.tsx
  components/common/Category.tsx
  components/main-page/MainInfo.tsx
  public/images/배너1.png
  public/images/배너2.png
  public/images/배너3.png
  public/images/배너4.png
  public/images/배너5.png
  public/images/배너6.png
  public/images/배너7.png
Labels: refactor

#97 [PFTF-91] 체험 상세 / 예약 현황 페이지 수정 및 리팩토링
  app/(app)/activity-detail/[activityId]/page.tsx
  app/(app)/globals.css
  app/(app)/reservation-status/page.tsx
  components/activity-detail/BannerImage.tsx
  components/activity-detail/ReservationModal/ReservationCounter/ReservationCounterPresenter.tsx
  components/activity-detail/ReservationModal/ReservationDate/ReservationDatePresenter.tsx
  components/activity-detail/ReviewList/index.tsx
  components/activity-detail/fetchCurrentUserData.ts
  components/activity-management/createOrUpdate/ActivityCreateOrUpdateForm.tsx
  components/common/ModalPortal/ModalLayOut.tsx
  components/common/ModalPortal/index.tsx
  components/common/ReviewModal/ReviewModal.tsx
  components/reservation-status/ReservationCalendar.tsx
  components/reservation-status/ReservationModalContents/ReservationCard.tsx
  components/reservation-status/ReservationModalContents/ReservationCardList.tsx
  components/reservation-status/ReservationModalContents/index.tsx
  components/reservation-status/StatusChip.tsx
  components/reservation-status/StatusChipList.tsx
  components/reservation-status/reservationStatusTypes.ts
Labels: refactor

#111 로그인 오류 제거
  auth.ts
  util/actions.ts
Labels: refactor

#118 체험 상세 / 예약 현황 페이지 버그 픽스 및 기능 추가
  app/(app)/reservation-status/page.tsx
  components/activity-detail/ReservationModal/ReservationDate/ReservationDate.tsx
  components/activity-detail/ReservationModal/ReservationDate/ReservationDatePresenter.tsx
  components/activity-detail/ReservationModal/index.tsx
  components/reservation-status/ReservationCalendar.tsx
  components/reservation-status/ReservationStatus.tsx
  components/reservation-status/StatusChipList.tsx
Labels: bug, page

#116 배너 이미지 수정 및 Dropdown 수정
  components/common/Banner.tsx
  components/main-page/MainInfo.tsx
Labels: refactor

#126 예약 내역 페이지 (버튼 조정 및 픽스) 및 알림 (토글 및 알림 내역) 픽스
  components/common/GNB/auth/AlertMenu.tsx
  components/common/NotificationModal/NotificationModal.tsx
  components/reservation/ReservationCanvanCard.tsx
Labels: bug

#106 [PFTF-105] readme 간략한 작성
  README.md
Labels: documentation

#128 favicon 추가
  app/favicon.ico
Labels: refactor

#137 헤더 알림 ping 추가
  components/common/GNB/auth/AlertMenu.tsx
  components/common/svg/AlertSvg.tsx
Labels: refactor
